In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sla

In [5]:
def escalonaResolve(A,b):
    Ab = np.c_[A,b]
    n = len(A)
    
    for c in range(n-1):  
        for l in range(c+1,n):
            p = np.abs(Ab[c:,c]).argmax() + c
            Ab[[c,p]] = Ab[[p,c]]
            Ab[l] = Ab[l] - (Ab[l,c]/Ab[c,c])*Ab[c]
            
    C = Ab[:,:-1]
    d = Ab[:,-1]
    n1 = len(d)
    x = np.empty(n1)
    
    if(C[-1,-1] == 0):
        return "Matriz singular"
    
    x[-1] = d[-1]/C[-1,-1]

    for i in range(n1-2, -1, -1):
         x[i] = (d[i] - np.sum(C[i,i+1:]*x[i+1:]))/C[i,i]
    return x

## **Exercício 1**

### **a)**

In [8]:
A = np.array([[1,1,1],[4,4,2],[2,1,-1]])
b = np.array([1,2,0])
escalonaResolve(A,b)

'Matriz singular'

In [7]:
sla.solve(A,b)

array([ 1., -1.,  1.])

### **b)**

In [9]:
A = np.array([[7,-7,1],[-3,3,2],[7,7,-72]])
b = np.array([1,2,7])
escalonaResolve(A,b)

array([5.64285714, 5.64285714, 1.        ])

In [10]:
sla.solve(A,b)

array([5.64285714, 5.64285714, 1.        ])

### **c)**

In [11]:
A = np.array([[1,2,3,4],[2,2,3,4],[3,3,3,4],[4,4,4,4]])
b = np.array([20,22,22,24])
escalonaResolve(A,b)

array([ 2., -2.,  2.,  4.])

In [12]:
sla.solve(A,b)

array([ 2., -2.,  2.,  4.])