In [1]:
import numpy as np
import scipy.linalg as sla

## **Exercício 1.1**

### **a)**

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])

In [3]:
np.linalg.matrix_rank(A)

2

In [4]:
np.linalg.matrix_rank(np.c_[A, b])

2

In [5]:
A.shape[1]

3

### **b)**

In [6]:
A = np.array([[2, 3], [-4, -6]])
b = np.array([10, -10])

In [7]:
np.linalg.matrix_rank(A)

1

In [8]:
np.linalg.matrix_rank(np.c_[A, b])

2

In [9]:
A.shape[1]

2

## **Exercício 1.2**

In [10]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    
    #Cria a martiz do tamanho do array b
    x = np.empty(n)
    
    #Calculo da icognita de maior indice 
    x[-1] = b[-1]/A[-1, -1]
    
    print("--------------------------------------")
    print("Icógnita com maior indice: ", b[-1], "/", A[-1, -1])
    print("Resultado: ", x[-1])
    print("--------------------------------------")
    
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
        
        print("Calculando a icógnita: ", ": ", "(",b[i], "-", "sum(",A[i,i+1:],"*",x[i+1:],")","/",A[i,i])
        print("Resultado: ", x[i])
        print("--------------------------------------")
        
    return x

In [11]:
A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])
b = np.array([-10,-1,3,2])

In [12]:
x = sist_lin_tri_sup(A,b)
x

--------------------------------------
Icógnita com maior indice:  2 / 2
Resultado:  1.0
--------------------------------------
Calculando a icógnita:  :  ( 3 - sum( [-5] * [1.] ) / 4
Resultado:  2.0
--------------------------------------
Calculando a icógnita:  :  ( -1 - sum( [ 1 -2] * [2. 1.] ) / 1
Resultado:  -1.0
--------------------------------------
Calculando a icógnita:  :  ( -10 - sum( [ 4 -5  1] * [-1.  2.  1.] ) / 3
Resultado:  1.0
--------------------------------------


array([ 1., -1.,  2.,  1.])

In [13]:
A.dot(x)

array([-10.,  -1.,   3.,   2.])

## **Exercício 1.3**

In [14]:
def sist_lin_tri_inf(A,b):
    n = len(b)
    
    #Cria a martiz do tamanho do array b
    x = np.empty(n)
    
    #Calculo da icognita de menor indice 
    x[0] = b[0]/A[0, 0]
    
    print("--------------------------------------")
    print("Icógnita de menor indice: ", b[0],"/",A[0, 0])
    print("Resultado: ", x[0])
    print("--------------------------------------")
    
    
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
        
        print("Calculando a incógnita: ", "(",b[i], "-", "sum(",A[i,:i],"*",x[:i],")","/",A[i,i])
        print("Resultado: ", x[i])
        print("--------------------------------------")
        
    return x

In [15]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b = np.array([4,2,4,2])

In [16]:
x = sist_lin_tri_inf(A,b)
x

--------------------------------------
Icógnita de menor indice:  4 / 3
Resultado:  1.3333333333333333
--------------------------------------
Calculando a incógnita:  ( 2 - sum( [2] * [1.33333333] ) / 1
Resultado:  -0.6666666666666665
--------------------------------------
Calculando a incógnita:  ( 4 - sum( [1 0] * [ 1.33333333 -0.66666667] ) / 1
Resultado:  2.666666666666667
--------------------------------------
Calculando a incógnita:  ( 2 - sum( [1 1 1] * [ 1.33333333 -0.66666667  2.66666667] ) / 1
Resultado:  -1.333333333333334
--------------------------------------


array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [17]:
A.dot(x)

array([4., 2., 4., 2.])

## **Exercício 1.4**

In [18]:
def sist_lin_diagonal(A,b): return b/A.diagonal()

In [19]:
def verificar_matriz(A,b):

    sup = True
    inf = True

    for i in range(A.shape[0]):
        for j in range(i+1, A.shape[1]):
            if A[i,j] != 0:
                inf = False

    for i in range(1, A.shape[0]):
        for j in range(0, i):
            if A[i,j] != 0:
                sup = False

    if sup and inf:
        print('\033[1m', "Matriz linear Diagonal", '\033[0m')
        print()
        print("--------------------------------------")
        return sist_lin_diagonal(A,b)
    
    else:
        if sup:
            print('\033[1m', "Matriz triangular superior", '\033[0m')
            print()
            return sist_lin_tri_sup(A,b)
        
        if inf:
            print('\033[1m', "Matriz triangular inferior", '\033[0m')
            print()
            return sist_lin_tri_inf(A,b)

### **Matriz Diagonal**

In [20]:
A = np.diag([1,4,2])
b = np.array([4, 2, 2])

In [21]:
verificar_matriz(A,b)

 Matriz linear Diagonal 

--------------------------------------


array([4. , 0.5, 1. ])

### **Matriz Triangular Superior**

In [22]:
A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])
b = np.array([-10,-1,3,2])

In [23]:
verificar_matriz(A,b)

 Matriz triangular superior 

--------------------------------------
Icógnita com maior indice:  2 / 2
Resultado:  1.0
--------------------------------------
Calculando a icógnita:  :  ( 3 - sum( [-5] * [1.] ) / 4
Resultado:  2.0
--------------------------------------
Calculando a icógnita:  :  ( -1 - sum( [ 1 -2] * [2. 1.] ) / 1
Resultado:  -1.0
--------------------------------------
Calculando a icógnita:  :  ( -10 - sum( [ 4 -5  1] * [-1.  2.  1.] ) / 3
Resultado:  1.0
--------------------------------------


array([ 1., -1.,  2.,  1.])

### **Matriz Triangular Inferior**

In [24]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b = np.array([4,2,4,2])

In [25]:
verificar_matriz(A,b)

 Matriz triangular inferior 

--------------------------------------
Icógnita de menor indice:  4 / 3
Resultado:  1.3333333333333333
--------------------------------------
Calculando a incógnita:  ( 2 - sum( [2] * [1.33333333] ) / 1
Resultado:  -0.6666666666666665
--------------------------------------
Calculando a incógnita:  ( 4 - sum( [1 0] * [ 1.33333333 -0.66666667] ) / 1
Resultado:  2.666666666666667
--------------------------------------
Calculando a incógnita:  ( 2 - sum( [1 1 1] * [ 1.33333333 -0.66666667  2.66666667] ) / 1
Resultado:  -1.333333333333334
--------------------------------------


array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])