In [30]:
import numpy as np
import scipy.linalg as sla

In [31]:
def sist_lin_tri_sup(A, b):
    n = len(b)
    x = np.empty(n)
    
    x[-1] = b[-1]/A[-1, -1]
    
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [32]:
def sist_lin_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    
    x[0] = b[0]/A[0, 0]
    
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
    return x

In [33]:
def pivotize(m):
    n = len(m)
    ID = [[float(i == j) for i in range(n)] for j in range(n)]
    for j in range(n):
        row = max(range(j, n), key=lambda i: abs(m[i][j]))
        if j != row:
            ID[j], ID[row] = ID[row], ID[j]
    return ID

In [34]:
def LU(A):
    n = len(A)
    L = [[0.0] * n for i in range(n)]
    U = [[0.0] * n for i in range(n)]
    
    P = pivotize(A)
    A2 = np.array(P)@np.array(A)
    
    for j in range(n):
        L[j][j] = 1.0
        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = A2[i][j] - s1
            
        for i in range(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            L[i][j] = (A2[i][j] - s2) / U[j][j]
    return (np.array(L), np.array(U), np.array(P))

In [35]:
def dec_LU(L, U, P, b):
    Pb = P@b
    y = sist_lin_tri_inf(L, Pb)
    x = sist_lin_tri_sup(U, y)
    return x

## **Exercício 1.1**

## ***(a)***

In [36]:
A = np.array([[1,1,1],[4,4,2],[2,1,-1]])
b = np.array([1,2,0])
L, U, P = LU(A)
dec_LU(L, U, P, b)

<ipython-input-34-a002e915eb02>:17: RuntimeWarning: invalid value encountered in double_scalars
  L[i][j] = (A2[i][j] - s2) / U[j][j]
<ipython-input-34-a002e915eb02>:17: RuntimeWarning: divide by zero encountered in double_scalars
  L[i][j] = (A2[i][j] - s2) / U[j][j]


array([nan, nan, nan])

In [37]:
L_U, piv = sla.lu_factor(A)
sla.lu_solve((L_U, piv), b)

array([ 1., -1.,  1.])

## ***(b)***

In [38]:
A = np.array([[7,-7,1],[-3,3,2],[7,7,-72]])
b = np.array([1,2,7])
L, U, P = LU(A)
dec_LU(L,U,P,b)

array([5.64285714, 5.64285714, 1.        ])

In [39]:
L_U, piv = sla.lu_factor(A)
sla.lu_solve((L_U, piv), b)

array([5.64285714, 5.64285714, 1.        ])

## ***(c)***

In [40]:
A = np.array([[1,2,3,4],[2,2,3,4],[3,3,3,4],[4,4,4,4]])
b = np.array([20,22,22,24])
L, U, P = LU(A)
dec_LU(L, U, P, b)

array([ 2., -2.,  2.,  4.])

In [41]:
L_U, piv = sla.lu_factor(A)
sla.lu_solve((L_U, piv), b)

array([ 2., -2.,  2.,  4.])